/**
 * Copyright (c) 2012, WonderBuilders, Inc., All Rights Reserved
 */
package com.wonderbuilders.modules.animation.client;

import com.wonderbuilders.modules.animation.common.EZScriptAnimationControl;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Vladimir Djurovic
 */
public class EZScriptAnimationPanel extends javax.swing.JPanel implements DocumentListener {

    /**
     * Creates new form EZScriptAnimationPanel
     * 
     * @param control EZScript control object
     */
    public EZScriptAnimationPanel(EZScriptAnimationControl control) {
        initComponents();
        if(control != null){
            functionField.setText(control.getFunction());
            commandField.setText(control.getCommand());
        }
        functionField.getDocument().addDocumentListener(this);
        commandField.getDocument().addDocumentListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptFunctionLabel = new javax.swing.JLabel();
        functionField = new javax.swing.JTextField();
        commandLabel = new javax.swing.JLabel();
        commandField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/wonderbuilders/modules/animation/client/resources/strings"); // NOI18N
        scriptFunctionLabel.setText(bundle.getString("EZScriptAnimationPanel.scriptFunctionLabel.text")); // NOI18N
        add(scriptFunctionLabel);

        functionField.setColumns(10);
        add(functionField);

        commandLabel.setText(bundle.getString("EZScriptAnimationPanel.commandLabel.text")); // NOI18N
        add(commandLabel);

        commandField.setColumns(10);
        add(commandField);

        removeButton.setText(bundle.getString("EZScriptAnimationPanel.removeButton.text")); // NOI18N
        removeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton);
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        ((AdvancedContainerPanel)getParent()).removeChildPanel(this);
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * Returns EZScript control data based on panel contents.
     * 
     * @return control data
     */
    public EZScriptAnimationControl getControlData(){
        EZScriptAnimationControl control = new EZScriptAnimationControl();
        control.setFunction(functionField.getText());
        control.setCommand(commandField.getText());
        
        return control;
    }
    
    /**
     * Mark panel as dirty.
     */
    public void markDirty(){
        ((AdvancedContainerPanel)getParent()).markDirty();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commandField;
    private javax.swing.JLabel commandLabel;
    private javax.swing.JTextField functionField;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel scriptFunctionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        markDirty();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        markDirty();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        markDirty();
    }
}
