/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IntroTestSection.java
 *
 * Created on Oct 18, 2011, 11:34:09 AM
 */
package org.jdesktop.wonderland.modules.clienttest.test.ui;

import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.wonderland.client.jme.LogViewer;
import org.json.simple.JSONObject;

/**
 *
 * @author jkaplan
 */
public class ResultsSection extends javax.swing.JPanel
    implements TestSection 
{
    private static final ResourceBundle BUNDLE = ResourceBundle.getBundle(
            "org/jdesktop/wonderland/modules/clienttest/test/ui/resources/Bundle");
    

    /** Creates new form IntroTestSection */
    public ResultsSection() {
    }

    public void initialize(JSONObject config) {
        initComponents();
    }

    public String getName() {
        return BUNDLE.getString("Results");
    }

    public JPanel getPanel() {
        return this;
    }

    public void sectionVisible() {
        StringBuilder text = new StringBuilder();
        text.append(BUNDLE.getString("ResultsText"));
        text.append("<table>");
        for (TestSection section : TestManager.INSTANCE.getSections()) {
            if (section instanceof RunnableTestSection) {
                text.append("<tr>").append("<td>");
                text.append(TestsSection.resultImage(((RunnableTestSection) section).getResult()));
                text.append("</td><td><h2>");
                text.append(section.getName());
                text.append("</h2></td>").append("</tr>");
            }
        }
        text.append("</table>");
        
        textPane.setText(text.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JEditorPane();
        detailsButton = new javax.swing.JButton();
        emailButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jdesktop/wonderland/modules/clienttest/test/ui/resources/Bundle"); // NOI18N
        textPane.setContentType(bundle.getString("ResultsSection.textPane.contentType")); // NOI18N
        textPane.setEditable(false);
        jScrollPane1.setViewportView(textPane);

        detailsButton.setText(bundle.getString("ResultsSection.detailsButton.text")); // NOI18N
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        emailButton.setText(bundle.getString("ResultsSection.emailButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(detailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailButton)
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsButton)
                    .addComponent(emailButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        JOptionPane.showMessageDialog(this, TestManager.INSTANCE.getLog());
    }//GEN-LAST:event_detailsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailsButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane textPane;
    // End of variables declaration//GEN-END:variables

}
