/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jdesktop.wonderland.modules.isocial.scavenger.client;

import javax.swing.JRadioButton;
import org.jdesktop.wonderland.modules.isocial.scavenger.client.components.QuestionComponentProperties;

/**
 *
 * @author vlada
 */
public class MultipleChoiceConfigPanel extends javax.swing.JPanel {
    
    private QuestionComponentProperties.MultiChoicePanel parent;

    /**
     * Creates new form MultipleChoiceConfigPanel
     */
    public MultipleChoiceConfigPanel(QuestionComponentProperties.MultiChoicePanel parent) {
        initComponents();
        this.parent = parent;
    }
    
    public int getAnswerWidth(){
        return answerField.getWidth();
    }
    
    public int getFeedbackWidth(){
        return feedbackField.getWidth();
    }
    
    public int getCorrectWidth(){
        return correctRB.getWidth();
    }
    
    public String getAnswer(){
        return answerField.getText();
    }
    
    public boolean isCorrect(){
        return correctRB.isSelected();
    }

    public JRadioButton getCorrectRB() {
        return correctRB;
    }
    
    public String getFeedback(){
        String feedback = feedbackField.getText();
        if(feedback == null){
            feedback = "";
        }
        return feedback;
        
    }
    
    public void setAnswer(String answer){
        answerField.setText(answer);
    }
    
    public void setFeedback(String feedback){
        feedbackField.setText(feedback);
    }
    
    public void setCorrect(boolean status){
        correctRB.setSelected(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        answerField = new javax.swing.JTextField();
        correctRB = new javax.swing.JRadioButton();
        feedbackField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        answerField.setColumns(15);
        answerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                answerFieldKeyPressed(evt);
            }
        });
        add(answerField);

        correctRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctRBActionPerformed(evt);
            }
        });
        add(correctRB);

        feedbackField.setColumns(15);
        feedbackField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackFieldActionPerformed(evt);
            }
        });
        add(feedbackField);

        removeButton.setText("x");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton);
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       parent.removeRow(this);
       parent.setDirty();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void correctRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctRBActionPerformed
        parent.setDirty();
    }//GEN-LAST:event_correctRBActionPerformed

    private void answerFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerFieldKeyPressed
        parent.setDirty();
    }//GEN-LAST:event_answerFieldKeyPressed

    private void feedbackFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackFieldActionPerformed
        parent.setDirty();
    }//GEN-LAST:event_feedbackFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JRadioButton correctRB;
    private javax.swing.JTextField feedbackField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
