
/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.rockwellcollins.stickynote.client;

import java.util.logging.Logger;
import javax.swing.JWindow;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jdesktop.wonderland.modules.rockwellcollins.stickynote.client.cell.SectionStyledStickyNoteCell;
import org.jdesktop.wonderland.modules.rockwellcollins.stickynote.common.cell.SectionStyledStickyNoteCellClientState;
import org.jdesktop.wonderland.modules.rockwellcollins.stickynote.common.cell.StickyNoteTypes;
import java.awt.Font;

/**
 * The parent jpanel to hold StickyNotePanels.
 * @author Xiuzhen 
 */
public class SectionStyledStickyNoteParentPanel  extends javax.swing.JPanel {

    public interface Container {

        public void validate();

        public void setOrtho(boolean ortho);
    }
    private JFrame frame;
    private Container container;
    private SectionStyledStickyNoteCell cell;
    private SectionStyledStickyNotePanel child;
    /** The logger used by this class */
    private static final Logger logger = Logger.getLogger(StickyNoteParentPanel.class.getName());

    /** Creates new form GenericStickyNotePanel */
    public SectionStyledStickyNoteParentPanel() {
        initComponents();
        this.setFont(new Font("sansserif", Font.BOLD, 64));
    }

    /** Creates new form GenericStickyNotePanel */
    public SectionStyledStickyNoteParentPanel(SectionStyledStickyNoteCell cell, SectionStyledStickyNoteCellClientState state) {
        this();
        this.cell = cell;
        if (state.getNoteType().equals(StickyNoteTypes.SECTION_STYLED)) {
            child = new SectionStyledStickyNotePanel(cell, state, this);
        }

        else {
            logger.severe("Unrecognized note type: " + state.getNoteType());
        }
        add((JPanel) child);
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    public void setContainer(Container container) {
        this.container = container;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 153));
        setPreferredSize(null);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
    }// </editor-fold>

    private void formFocusGained(java.awt.event.FocusEvent evt) {
    }
    private boolean ortho = false;

    // Variables declaration - do not modify
    // End of variables declaration
    public static void main(String args[]) {
        JWindow j = new JWindow();
        System.out.println(j.getLayout());
        j.add(new SectionStyledStickyNoteParentPanel());
        j.pack();
        j.setVisible(true);
    }

    public SectionStyledStickyNotePanel getChild() {
        return child;
    }
}
