/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.timelineproviders.client;

import org.jdesktop.wonderland.modules.timelineproviders.common.FlickrConstants;

/**
 *
 * @author nsimpson
 */
public class NYTimesConfigurationPanel extends javax.swing.JPanel {
    private boolean ok = false;

    public NYTimesConfigurationPanel() {
        initComponents();

        if (System.getProperty("nytimes.api.key") != null) {
            remove(apiKeyField);
            remove(apiKeyLabel);
        }
    }

    public void setAPIKey(String apiKey) {
        apiKeyField.setText(apiKey);
    }

    public String getAPIKey() {
        return apiKeyField.getText();
    }

    public void setQueryText(String text) {
        searchTextField.setText(text);
    }

    public String getQueryText() {
        return searchTextField.getText();
    }

    public int getResultLimit() {
        int limit = Integer.MAX_VALUE;

        if (return1RadioButton.isSelected()) {
            limit = 1;
        } else if (return2RadioButton.isSelected()) {
            limit = 2;
        } else if (return4RadioButton.isSelected()) {
            limit = 4;
        } else if (return6RadioButton.isSelected()) {
            limit = 6;
        } else if (return8RadioButton.isSelected()) {
            limit = 8;
        }
        return limit;
    }

    public void setResultLimit(int limit) {
        if (limit == 1) {
            return1RadioButton.setSelected(true);
        } else if (limit == 2) {
            return2RadioButton.setSelected(true);
        } else if (limit == 4) {
            return4RadioButton.setSelected(true);
        } else if (limit == 6) {
            return6RadioButton.setSelected(true);
        } else if (limit == 8) {
            return8RadioButton.setSelected(true);
        } else if (limit == Integer.MAX_VALUE) {
            returnAllRadioButton.setSelected(true);
        }
    }
    
    public boolean isOK() {
        return ok;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagsOrTextButtonGroup = new javax.swing.ButtonGroup();
        resultsButtonGroup = new javax.swing.ButtonGroup();
        searchByButtonGroup = new javax.swing.ButtonGroup();
        returnButtonGroup = new javax.swing.ButtonGroup();
        configurationLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        returnLabel = new javax.swing.JLabel();
        return1RadioButton = new javax.swing.JRadioButton();
        return2RadioButton = new javax.swing.JRadioButton();
        return4RadioButton = new javax.swing.JRadioButton();
        return6RadioButton = new javax.swing.JRadioButton();
        return8RadioButton = new javax.swing.JRadioButton();
        returnAllRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyField = new javax.swing.JTextField();

        configurationLabel.setFont(configurationLabel.getFont().deriveFont(configurationLabel.getFont().getStyle() | java.awt.Font.BOLD));
        configurationLabel.setText("New York Times Query Configuration");

        searchLabel.setText("Search for: ");

        searchTextField.setText("horses and boats");

        returnLabel.setText("Return:");

        returnButtonGroup.add(return1RadioButton);
        return1RadioButton.setSelected(true);
        return1RadioButton.setText("1");

        returnButtonGroup.add(return2RadioButton);
        return2RadioButton.setText("2");

        returnButtonGroup.add(return4RadioButton);
        return4RadioButton.setText("4");

        returnButtonGroup.add(return6RadioButton);
        return6RadioButton.setText("6");

        returnButtonGroup.add(return8RadioButton);
        return8RadioButton.setText("8");

        returnButtonGroup.add(returnAllRadioButton);
        returnAllRadioButton.setText("All items");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        apiKeyLabel.setText("API Key:");

        apiKeyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apiKeyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(configurationLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchLabel)
                            .addComponent(apiKeyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(apiKeyField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(returnLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(return1RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(return2RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(return4RadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(return6RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(return8RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returnAllRadioButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(146, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configurationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(return2RadioButton)
                            .addComponent(return1RadioButton)
                            .addComponent(return4RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnAllRadioButton)
                            .addComponent(return6RadioButton)
                            .addComponent(return8RadioButton)))
                    .addComponent(returnLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        ok = true;
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ok = false;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void apiKeyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apiKeyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apiKeyFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apiKeyField;
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel configurationLabel;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup resultsButtonGroup;
    private javax.swing.JRadioButton return1RadioButton;
    private javax.swing.JRadioButton return2RadioButton;
    private javax.swing.JRadioButton return4RadioButton;
    private javax.swing.JRadioButton return6RadioButton;
    private javax.swing.JRadioButton return8RadioButton;
    private javax.swing.JRadioButton returnAllRadioButton;
    private javax.swing.ButtonGroup returnButtonGroup;
    private javax.swing.JLabel returnLabel;
    private javax.swing.ButtonGroup searchByButtonGroup;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.ButtonGroup tagsOrTextButtonGroup;
    // End of variables declaration//GEN-END:variables
}
