/**
 * Open Wonderland
 *
 * Copyright (c) 2011, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */

/*
 * IntroTestSection.java
 *
 * Created on Oct 18, 2011, 11:34:09 AM
 */
package org.jdesktop.wonderland.modules.clienttest.test.ui;

import java.util.ResourceBundle;
import javax.swing.JPanel;
import org.json.simple.JSONObject;

/**
 *
 * @author jkaplan
 */
public class ResultsSection extends javax.swing.JPanel
    implements TestSection 
{
    private static final ResourceBundle BUNDLE = ResourceBundle.getBundle(
            "org/jdesktop/wonderland/modules/clienttest/test/ui/resources/Bundle");
    

    /** Creates new form IntroTestSection */
    public ResultsSection() {
    }

    public void initialize(JSONObject config) {
        initComponents();
    }

    public String getName() {
        return BUNDLE.getString("Results");
    }

    public JPanel getPanel() {
        return this;
    }

    public void sectionVisible() {
        StringBuilder text = new StringBuilder();
        text.append(BUNDLE.getString("ResultsText"));
        text.append("<table>");
        for (TestSection section : TestManager.INSTANCE.getSections()) {
            if (section instanceof RunnableTestSection) {
                text.append("<tr>").append("<td>");
                text.append(TestsSection.resultImage(((RunnableTestSection) section).getResult()));
                text.append("</td><td><h2>");
                text.append(section.getName());
                text.append("</h2></td>").append("</tr>");
            }
        }
        text.append("</table>");
        
        textPane.setText(text.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JEditorPane();
        detailsButton = new javax.swing.JButton();
        postButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jdesktop/wonderland/modules/clienttest/test/ui/resources/Bundle"); // NOI18N
        textPane.setContentType(bundle.getString("ResultsSection.textPane.contentType")); // NOI18N
        textPane.setEditable(false);
        jScrollPane1.setViewportView(textPane);

        detailsButton.setText(bundle.getString("ResultsSection.detailsButton.text")); // NOI18N
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        postButton.setText(bundle.getString("ResultsSection.postButton.text")); // NOI18N
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(detailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(postButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postButton)
                    .addComponent(detailsButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        LogViewerFrame lvf = new LogViewerFrame(TestManager.INSTANCE.getLog());
        lvf.pack();
        lvf.setVisible(true);
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        SubmitLogFrame slf = new SubmitLogFrame(TestManager.INSTANCE.getLog());
        slf.pack();
        slf.setVisible(true);
    }//GEN-LAST:event_postButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton postButton;
    private javax.swing.JEditorPane textPane;
    // End of variables declaration//GEN-END:variables

}
