/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JothControlPanel.java
 *
 * Created on Jun 8, 2009, 5:56:14 PM
 */

package org.jdesktop.wonderland.modules.joth.client;

/**
 *
 * @author dj
 */
public class JothControlPanel extends javax.swing.JPanel {

    public interface ControlPanelContainer {
        public void newGame();
    }

    /** The game that contains this control panel. */
    private ControlPanelContainer container;

    /** Creates new form JothControlPanel */
    public JothControlPanel() {
        initComponents();

	newGameButton.setToolTipText("Start a new game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

    }

    public void setContainer (ControlPanelContainer container) {
        this.container = container;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turnMessage = new javax.swing.JLabel();
        whiteCountMessage = new javax.swing.JLabel();
        blackCountMessage = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        newGameButton.setText("New Game");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(blackCountMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(whiteCountMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(turnMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(newGameButton)
                    .add(errorMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(turnMessage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(whiteCountMessage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(blackCountMessage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(newGameButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(errorMessage)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blackCountMessage;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel turnMessage;
    private javax.swing.JLabel whiteCountMessage;
    // End of variables declaration//GEN-END:variables

    public void clearError () {
        errorMessage.setText("");
    }

    public void error (String message) {
        errorMessage.setText("Error: " + message);
    }

    public void displayCounts (int whiteCount, int blackCount) {
        whiteCountMessage.setText("White Pieces: " + whiteCount);
        blackCountMessage.setText("Black Pieces: " + blackCount);
    }

    public void setTurn (String whoseTurn) {
        turnMessage.setText("It is " + whoseTurn + "'s turn.");
    }

    public void notifyGameOver (String msg) {
        errorMessage.setText(msg);
        turnMessage.setText("");
    }

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {
        container.newGame();
    }
}
