/**
  * iSocial Project
  * http://isocial.missouri.edu
  *
  * Copyright (c) 2011, University of Missouri iSocial Project, All 
  * Rights Reserved
  *
  * Redistributions in source code form must reproduce the above
  * copyright and this condition.
  *
  * The contents of this file are subject to the GNU General Public
  * License, Version 2 (the "License"); you may not use this file
  * except in compliance with the License. A copy of the License is
  * available at http://www.opensource.org/licenses/gpl-license.php.
  *
  * The iSocial project designates this particular file as
  * subject to the "Classpath" exception as provided by the iSocial
  * project in the License file that accompanied this code.
  */

package org.jdesktop.wonderland.modules.mediaboard.client;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ryan
 */
public class TakePhotoDialog extends javax.swing.JDialog  implements ActionListener {

    /** Creates new form TakePhotoDialog */
    ImageCaptureHarness ich = null;

    public TakePhotoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ich = new ImageCaptureHarness();
        this.setContentPane(ich);

        ich.addAcceptButtonActionPerformed(this);
        JOptionPane j;
        setVisible(true);
    }

    public String getPicture() {

        this.setModal(true);
      //  ImageCapturePanel ich = new ImageCapturePanel(new WhiteboardDocument());
       // ich.setMinimumSize(new Dimension(500, 600));
        //ich.setPreferredSize(new Dimension(500, 600));
        //this.setContentPane(ich);

        this.setPreferredSize(new Dimension(500, 600));
        this.setMinimumSize(new Dimension(500, 600));
        //ich.addAcceptButtonActionPerformed(new ActionListener() {
          //  public void actionPerformed(ActionEvent e) {
            //    setVisible(false);
            //}
        //});

        setVisible(true);
        return ich.getPictureURLAsString();
    }

    /**
     * This method will make the dialog appear
     * @return the url of the picture in string form
     */
    public static String takePicture() {
        //url filename of picture on webdav
        String url = "";

        //null frame parent
        Frame parent = null;

        //dialog to hold the ich panel

        final JDialog dialog = new JDialog(parent, true);

        //panel that goes into dialog container
        /*ImageCapturePanel ich = new ImageCapturePanel();
        ich.setMinimumSize(new Dimension(300, 900));
        ich.setPreferredSize(new Dimension(300, 900));

        //you can only add a JPanel here, NEVER a JFrame.

        dialog.setContentPane(ich);

        dialog.setPreferredSize(new Dimension(300, 900));
        dialog.setMinimumSize(new Dimension(300, 900));

        ich.addAcceptButtonActionPerformed(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                dialog.setVisible(false);
            }
        });        

        */

        // wait for picture to be taken
        dialog.setVisible(true);

        //url = ich.getPictureURLAsString();

        return url;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    public void actionPerformed(ActionEvent e) {
        this.setVisible(false);
    //    this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
