/**
 * Open Wonderland
 *
 * Copyright (c) 2011-12, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */
package org.jdesktop.wonderland.modules.webcaster.client;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 * Control panel for Webcaster. Provides button to start & stop webcasting,
 * and function to set the name of the stream.
 * @author Christian O'Connell
 * @author Bernard Horan
 */
public class WebcasterControlPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(
            WebcasterControlPanel.class.getName());
    private static final ResourceBundle bundle = ResourceBundle.getBundle("org/jdesktop/wonderland/modules/webcaster/client/resources/Bundle");
    private final WebcasterCell webcasterCell;

    /** Creates new form WebcasterControlPanel
     * @param cell the webcaster cell controlled by this panel
     */
    public WebcasterControlPanel(WebcasterCell cell, int streamID) {
        this.webcasterCell = cell;
        initComponents();
        streamField.setText(String.valueOf(streamID));
        previewPanel.add(cell.getCaptureComponent(), BorderLayout.CENTER);
        setRemoteWebcasting(cell.isRemoteWebcasting());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previewPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        streamLabel = new javax.swing.JLabel();
        streamField = new javax.swing.JTextField();
        webcastButton = new javax.swing.JToggleButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        previewPanel.setMaximumSize(new java.awt.Dimension(640, 360));
        previewPanel.setMinimumSize(new java.awt.Dimension(640, 360));
        previewPanel.setPreferredSize(new java.awt.Dimension(640, 360));
        previewPanel.setLayout(new java.awt.BorderLayout());
        add(previewPanel);

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        streamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streamLabel.setText(bundle.getString("STREAM NAME:")); // NOI18N
        streamLabel.setAlignmentX(0.5f);
        streamLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(streamLabel);

        streamField.setEditable(false);
        streamField.setMaximumSize(new Dimension(Integer.MAX_VALUE, streamField.getPreferredSize().height) );
        jPanel1.add(streamField);

        webcastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/webcaster/client/resources/icon.gif"))); // NOI18N
        webcastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webcastButtonActionPerformed(evt);
            }
        });
        jPanel1.add(webcastButton);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void webcast(boolean state) {
        webcasterCell.setWebcasting(state);
        //streamLabel.setEnabled(!webcasterCell.getWebcasting());
        //streamField.setEnabled(!webcasterCell.getWebcasting());
    }
    
    

    private void webcastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webcastButtonActionPerformed
        webcast(webcastButton.isSelected());
    }//GEN-LAST:event_webcastButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JTextField streamField;
    private javax.swing.JLabel streamLabel;
    private javax.swing.JToggleButton webcastButton;
    // End of variables declaration//GEN-END:variables

    final void setRemoteWebcasting(final boolean b) {
        LOGGER.warning("remoteWebcasting: " + b);
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                webcastButton.setEnabled(!b);
            }
        });
        
    }

    void updateWebcasting() {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                webcastButton.setSelected(webcasterCell.getWebcasting());
            }
        });

    }
}
