/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhysicsControlPanel.java
 *
 * Created on Aug 4, 2011, 1:47:07 PM
 */
package org.jdesktop.wonderland.modules.ezscript.client.simplephysics;

/**
 *
 * @author JagWire
 */
public class PhysicsControlPanel extends javax.swing.JPanel {

    /** Creates new form PhysicsControlPanel */
    public PhysicsControlPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        applyForceButton = new javax.swing.JButton();
        applyImpulseButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(200, 70));
        setSize(new java.awt.Dimension(200, 70));
        setLayout(new java.awt.GridBagLayout());

        addButton.setText("ARB");
        addButton.setToolTipText("Add Rigid Body");
        addButton.setPreferredSize(new java.awt.Dimension(64, 64));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new java.awt.GridBagConstraints());

        applyForceButton.setText("ACF");
        applyForceButton.setToolTipText("Apply Central Force");
        applyForceButton.setPreferredSize(new java.awt.Dimension(64, 64));
        add(applyForceButton, new java.awt.GridBagConstraints());

        applyImpulseButton.setText("AIF");
        applyImpulseButton.setToolTipText("Apply Impulse Force");
        applyImpulseButton.setPreferredSize(new java.awt.Dimension(64, 64));
        add(applyImpulseButton, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        new Thread(new Runnable() { 
            public void run() { 
                SimplePhysicsManager.INSTANCE.createRigidBody("BOX");
            }
        }).start();

    }//GEN-LAST:event_addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton applyForceButton;
    private javax.swing.JButton applyImpulseButton;
    // End of variables declaration//GEN-END:variables
}
