/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.topmap.client;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;


/**
 * A JPanel to be used as a HUD panel that displays a top map.
 *
 * @author Jordan Slott <jslott@dev.java.net>
 */
public class TopMapJPanel extends javax.swing.JPanel {

    // The width and height of the map image
    private static final int MAP_HEIGHT = 256;
    private static final int MAP_WIDTH = 256;

    // The buffered image in which to draw the camera scene
    private BufferedImage bufferedImage = null;

    // The component that displays the top map
    private CaptureJComponent mapComponent = null;

    /** Default constructor */
    public TopMapJPanel() {
        // Initialize the GUI
        initComponents();

        // Create the BufferedImage into which we will draw the camera scene
        bufferedImage = new BufferedImage(MAP_WIDTH, MAP_HEIGHT,
                BufferedImage.TYPE_INT_RGB);

        // Create and add a CaptureJPanel to the panel
        mapComponent = new CaptureJComponent(bufferedImage);
        mapComponent.setPreferredSize(new Dimension(MAP_WIDTH, MAP_HEIGHT));
        topMapPanel.add(mapComponent);
    }

    /**
     * Returns the CaptureJComponent which renders the map.
     *
     * @return The JComponent that renders the map
     */
    public CaptureJComponent getCaptureJComponent() {
        return mapComponent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topMapPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout());

        topMapPanel.setLayout(new java.awt.GridLayout());
        add(topMapPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel topMapPanel;
    // End of variables declaration//GEN-END:variables
}
