/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EventEditor.java
 *
 * Created on Jan 11, 2010, 5:40:46 AM
 */
package org.jdesktop.wonderland.modules.cmu.client.ui.events;

import org.jdesktop.wonderland.modules.cmu.client.CMUCell;
import org.jdesktop.wonderland.modules.cmu.common.events.ProximityEvent;
import org.jdesktop.wonderland.modules.cmu.common.events.WonderlandEventList;
import org.jdesktop.wonderland.modules.cmu.common.events.WonderlandEventResponse;

/**
 *
 * @author kevin
 */
public class EventEditor extends javax.swing.JFrame {

    private final CMUCell parentCell;

    /** Creates new form EventEditor */
    public EventEditor(CMUCell parentCell) {
        initComponents();
        this.parentCell = parentCell;
        this.populateResponseList();
    }

    public CMUCell getParentCell() {
        return parentCell;
    }

    private void populateResponseList() {
        for (WonderlandEventResponse response : this.getParentCell().getAllowedResponses()) {
            this.responseList.addItem(new ResponseMenuItem(response));
        }
    }

    public void applyList() {
        WonderlandEventList list = new WonderlandEventList();

        list.add(new ProximityEvent(((Integer) distanceSpinner.getValue()).intValue(), true,
                ((ResponseMenuItem)responseList.getSelectedItem()).getResponse()));

        this.getParentCell().setEventList(list);
    }

    private class ResponseMenuItem {
        private final WonderlandEventResponse response;
        public ResponseMenuItem(WonderlandEventResponse response) {
            this.response = response;
        }

        public WonderlandEventResponse getResponse() {
            return this.response;
        }

        @Override
        public String toString() {
            return this.response.getFunctionName();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        distanceSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        responseList = new javax.swing.JComboBox();

        jLabel1.setText("Distance:");

        jLabel2.setText("Function to call:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPressed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(distanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(responseList, 0, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(distanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(responseList, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonPressed
        this.applyList();
        this.setVisible(false);
    }//GEN-LAST:event_okButtonPressed

    private void cancelButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPressed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner distanceSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox responseList;
    // End of variables declaration//GEN-END:variables
}
