/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ColorThemeEditorPanel.java
 *
 * Created on Jan 11, 2012, 2:48:21 PM
 */
package com.wonderbuilders.modules.colortheme.client;

import com.wonderbuilders.modules.colortheme.common.ColorTheme;
import java.awt.Color;
import java.io.IOException;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Vladimir Djurovic
 */
public class ColorThemeEditorPanel extends javax.swing.JPanel {
    
     private static  final Logger logger = Logger.getLogger(ColorThemeEditorPanel.class.getName());
    
    private final Properties baseColors;
    private Map<String, String> colorMap;
    private String themeName;

    /** Creates new form ColorThemeEditorPanel */
    public ColorThemeEditorPanel(ColorTheme theme) {
        // load base color values from color.properties file
        baseColors = new Properties();
        try{
            baseColors.load(getClass().getResourceAsStream("/com/wonderbuilders/modules/colortheme/client/resources/colors.properties"));
            if(theme != null){
                colorMap = theme.getColorMap();
                themeName = theme.getThemeName();
            } 
            
        } catch(IOException ex){
            // report error and continue with default values
            logger.log(Level.SEVERE, "Could not load colors.properties file for color theme editor", ex);
        }
        initComponents();
    }
    
    /**
     * Sets background color based on property file configuration.
     * 
     * @param panel panel to set color for
     * @param key color key in property file
     */
    private void setColorForKey(JPanel panel,String key){
        if(baseColors.getProperty(key) != null){
            panel.setBackground(ColorThemeUtils.convertStringToColor(baseColors.getProperty(key)));
        }
    }
    
    /**
     * Set label text based on property file configuration.
     * 
     * @param label label to set text for
     * @param key color key in confoguration file
     */
    private void setTextForColorKey(JLabel label,String key){
        if(baseColors.getProperty(key) != null){
            label.setText(baseColors.getProperty(key));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorsPanel = new javax.swing.JPanel();
        baseColor1Box = new javax.swing.JPanel();
        baseColor1Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mapColor1Box = new javax.swing.JPanel();
        mapColor1Label = new javax.swing.JLabel();
        baseColor2Box = new javax.swing.JPanel();
        baseColor2Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mapColor2Box = new javax.swing.JPanel();
        mapColor2Label = new javax.swing.JLabel();
        baseColor4Box = new javax.swing.JPanel();
        baseColor4Label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mapColor4Box = new javax.swing.JPanel();
        mapColor4Label = new javax.swing.JLabel();
        baseColor3Box = new javax.swing.JPanel();
        baseColor3Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mapColor3Box = new javax.swing.JPanel();
        mapColor3Label = new javax.swing.JLabel();
        baseColor6Box = new javax.swing.JPanel();
        baseColor6Label = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mapColor6Box = new javax.swing.JPanel();
        mapColor6Label = new javax.swing.JLabel();
        mapColor5Label = new javax.swing.JLabel();
        mapColor5Box = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        baseColor5Label = new javax.swing.JLabel();
        baseColor5Box = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        themeTitleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        colorsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        baseColor1Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor1Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor1Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor1BoxLayout = new javax.swing.GroupLayout(baseColor1Box);
        baseColor1Box.setLayout(baseColor1BoxLayout);
        baseColor1BoxLayout.setHorizontalGroup(
            baseColor1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor1BoxLayout.setVerticalGroup(
            baseColor1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        baseColor1Label.setText("FFFFFF");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        mapColor1Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor1Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor1Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor1Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor1BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor1BoxLayout = new javax.swing.GroupLayout(mapColor1Box);
        mapColor1Box.setLayout(mapColor1BoxLayout);
        mapColor1BoxLayout.setHorizontalGroup(
            mapColor1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor1BoxLayout.setVerticalGroup(
            mapColor1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        mapColor1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor1Label.setText("FFFFFF");

        baseColor2Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor2Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor2Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor2BoxLayout = new javax.swing.GroupLayout(baseColor2Box);
        baseColor2Box.setLayout(baseColor2BoxLayout);
        baseColor2BoxLayout.setHorizontalGroup(
            baseColor2BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor2BoxLayout.setVerticalGroup(
            baseColor2BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        baseColor2Label.setText("FFFFFF");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        mapColor2Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor2Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor2Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor2Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor2BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor2BoxLayout = new javax.swing.GroupLayout(mapColor2Box);
        mapColor2Box.setLayout(mapColor2BoxLayout);
        mapColor2BoxLayout.setHorizontalGroup(
            mapColor2BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor2BoxLayout.setVerticalGroup(
            mapColor2BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        mapColor2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor2Label.setText("FFFFFF");

        baseColor4Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor4Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor4Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor4BoxLayout = new javax.swing.GroupLayout(baseColor4Box);
        baseColor4Box.setLayout(baseColor4BoxLayout);
        baseColor4BoxLayout.setHorizontalGroup(
            baseColor4BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor4BoxLayout.setVerticalGroup(
            baseColor4BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        baseColor4Label.setText("FFFFFF");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        mapColor4Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor4Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor4Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor4Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor4BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor4BoxLayout = new javax.swing.GroupLayout(mapColor4Box);
        mapColor4Box.setLayout(mapColor4BoxLayout);
        mapColor4BoxLayout.setHorizontalGroup(
            mapColor4BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor4BoxLayout.setVerticalGroup(
            mapColor4BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        mapColor4Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor4Label.setText("FFFFFF");

        baseColor3Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor3Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor3Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor3BoxLayout = new javax.swing.GroupLayout(baseColor3Box);
        baseColor3Box.setLayout(baseColor3BoxLayout);
        baseColor3BoxLayout.setHorizontalGroup(
            baseColor3BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor3BoxLayout.setVerticalGroup(
            baseColor3BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        baseColor3Label.setText("FFFFFF");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        mapColor3Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor3Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor3Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor3Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor3BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor3BoxLayout = new javax.swing.GroupLayout(mapColor3Box);
        mapColor3Box.setLayout(mapColor3BoxLayout);
        mapColor3BoxLayout.setHorizontalGroup(
            mapColor3BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor3BoxLayout.setVerticalGroup(
            mapColor3BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        mapColor3Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor3Label.setText("FFFFFF");

        baseColor6Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor6Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor6Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor6BoxLayout = new javax.swing.GroupLayout(baseColor6Box);
        baseColor6Box.setLayout(baseColor6BoxLayout);
        baseColor6BoxLayout.setHorizontalGroup(
            baseColor6BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor6BoxLayout.setVerticalGroup(
            baseColor6BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        baseColor6Label.setText("FFFFFF");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        mapColor6Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor6Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor6Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor6Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor6BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor6BoxLayout = new javax.swing.GroupLayout(mapColor6Box);
        mapColor6Box.setLayout(mapColor6BoxLayout);
        mapColor6BoxLayout.setHorizontalGroup(
            mapColor6BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor6BoxLayout.setVerticalGroup(
            mapColor6BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        mapColor6Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor6Label.setText("FFFFFF");

        mapColor5Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mapColor5Label.setText("FFFFFF");

        mapColor5Box.setBackground(new java.awt.Color(255, 255, 255));
        mapColor5Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapColor5Box.setPreferredSize(new java.awt.Dimension(50, 20));
        mapColor5Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapColor5BoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapColor5BoxLayout = new javax.swing.GroupLayout(mapColor5Box);
        mapColor5Box.setLayout(mapColor5BoxLayout);
        mapColor5BoxLayout.setHorizontalGroup(
            mapColor5BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        mapColor5BoxLayout.setVerticalGroup(
            mapColor5BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderbuilders/modules/colortheme/client/resources/MapsTo.png"))); // NOI18N

        baseColor5Label.setText("FFFFFF");

        baseColor5Box.setBackground(new java.awt.Color(255, 255, 255));
        baseColor5Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseColor5Box.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout baseColor5BoxLayout = new javax.swing.GroupLayout(baseColor5Box);
        baseColor5Box.setLayout(baseColor5BoxLayout);
        baseColor5BoxLayout.setHorizontalGroup(
            baseColor5BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        baseColor5BoxLayout.setVerticalGroup(
            baseColor5BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        setColorForKey(baseColor1Box, ColorThemeComponentConstants.KEY_BASE_COLOR_1);
        setTextForColorKey(baseColor1Label, ColorThemeComponentConstants.KEY_BASE_COLOR_1);
        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor1Box.getBackground());
            mapColor1Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor1Label.setText(colorMap.get(base));
        }
        setColorForKey(baseColor2Box, ColorThemeComponentConstants.KEY_BASE_COLOR_2);
        setTextForColorKey(baseColor2Label, ColorThemeComponentConstants.KEY_BASE_COLOR_2);
        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor2Box.getBackground());
            mapColor2Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor2Label.setText(colorMap.get(base));
        }
        setColorForKey(baseColor4Box, ColorThemeComponentConstants.KEY_BASE_COLOR_4);
        setTextForColorKey(baseColor4Label, ColorThemeComponentConstants.KEY_BASE_COLOR_4);
        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor4Box.getBackground());
            mapColor4Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor4Label.setText(colorMap.get(base));
        }
        setColorForKey(baseColor3Box, ColorThemeComponentConstants.KEY_BASE_COLOR_3);
        setTextForColorKey(baseColor3Label, ColorThemeComponentConstants.KEY_BASE_COLOR_3);
        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor3Box.getBackground());
            mapColor3Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor3Label.setText(colorMap.get(base));
        }
        setColorForKey(baseColor6Box, ColorThemeComponentConstants.KEY_BASE_COLOR_6);
        setTextForColorKey(baseColor6Label, ColorThemeComponentConstants.KEY_BASE_COLOR_6);
        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor6Box.getBackground());
            mapColor6Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor6Label.setText(colorMap.get(base));
        }
        setTextForColorKey(baseColor5Label, ColorThemeComponentConstants.KEY_BASE_COLOR_5);
        setColorForKey(baseColor5Box, ColorThemeComponentConstants.KEY_BASE_COLOR_5);

        javax.swing.GroupLayout colorsPanelLayout = new javax.swing.GroupLayout(colorsPanel);
        colorsPanel.setLayout(colorsPanelLayout);
        colorsPanelLayout.setHorizontalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor5Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor5Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor5Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(baseColor6Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseColor6Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(30, 30, 30)
                        .addComponent(mapColor6Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapColor6Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapColor5Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapColor4Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapColor3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapColor2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapColor1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );
        colorsPanelLayout.setVerticalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor1Label)
                    .addComponent(jLabel4)
                    .addComponent(mapColor1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor2Label)
                    .addComponent(jLabel7)
                    .addComponent(mapColor2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor3Label)
                    .addComponent(jLabel13)
                    .addComponent(mapColor3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor4Label)
                    .addComponent(jLabel10)
                    .addComponent(mapColor4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor4Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor5Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor5Label)
                    .addComponent(jLabel19)
                    .addComponent(mapColor5Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor5Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(baseColor6Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseColor6Label)
                    .addComponent(jLabel16)
                    .addComponent(mapColor6Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapColor6Label))
                .addContainerGap())
        );

        if(colorMap != null && !colorMap.isEmpty()){
            String base = ColorThemeUtils.convertColorToString(baseColor5Box.getBackground());
            mapColor5Box.setBackground(ColorThemeUtils.convertStringToColor(colorMap.get(base)));
            mapColor5Label.setText(colorMap.get(base));
        }

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/wonderbuilders/modules/colortheme/client/resources/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("ColorThemeEditorPanel.jLabel1.text")); // NOI18N

        themeTitleField.setText(bundle.getString("ColorThemeEditorDialog.themeTitleField.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("ColorThemeEditorPanel.jLabel2.text")); // NOI18N

        if(themeName != null && !themeName.isEmpty()){
            themeTitleField.setText(themeName);
        } else {
            themeTitleField.setText(ColorTheme.DEFAULT_THEME_NAME);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(themeTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(colorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(themeTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(colorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectNewColor(JPanel box){
        JColorChooser chooser = new JColorChooser();
        JDialog dialog = JColorChooser.createDialog(this, "Select color", true, chooser, null, null);
        dialog.setVisible(true);
        Color newColor = chooser.getColor();
        if(newColor != null){
            box.setBackground(newColor);
            box.repaint();
        }
    }
    
    /**
     * Returns color map for this editor.
     * @return 
     */
    public Map<String, String> getColorMap(){
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor1Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor1Box.getBackground()));
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor2Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor2Box.getBackground()));
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor3Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor3Box.getBackground()));
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor4Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor4Box.getBackground()));
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor5Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor5Box.getBackground()));
        colorMap.put(ColorThemeUtils.convertColorToString(baseColor6Box.getBackground()), ColorThemeUtils.convertColorToString(mapColor6Box.getBackground()));
        
        return colorMap;
    }
    
    public String getThemeName(){
        return themeTitleField.getText();
    }
    
    private void mapColor1BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor1BoxMouseClicked
        selectNewColor(mapColor1Box);
        mapColor1Label.setText(ColorThemeUtils.convertColorToString(mapColor1Box.getBackground()));
    }//GEN-LAST:event_mapColor1BoxMouseClicked

    private void mapColor2BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor2BoxMouseClicked
         selectNewColor(mapColor2Box);
         mapColor2Label.setText(ColorThemeUtils.convertColorToString(mapColor2Box.getBackground()));
    }//GEN-LAST:event_mapColor2BoxMouseClicked

    private void mapColor3BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor3BoxMouseClicked
        selectNewColor(mapColor3Box);
        mapColor3Label.setText(ColorThemeUtils.convertColorToString(mapColor3Box.getBackground()));
    }//GEN-LAST:event_mapColor3BoxMouseClicked

    private void mapColor4BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor4BoxMouseClicked
        selectNewColor(mapColor4Box);
        mapColor4Label.setText(ColorThemeUtils.convertColorToString(mapColor4Box.getBackground()));
    }//GEN-LAST:event_mapColor4BoxMouseClicked

    private void mapColor5BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor5BoxMouseClicked
        selectNewColor(mapColor5Box);
        mapColor5Label.setText(ColorThemeUtils.convertColorToString(mapColor5Box.getBackground()));
    }//GEN-LAST:event_mapColor5BoxMouseClicked

    private void mapColor6BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapColor6BoxMouseClicked
        selectNewColor(mapColor6Box);
        mapColor6Label.setText(ColorThemeUtils.convertColorToString(mapColor6Box.getBackground()));
    }//GEN-LAST:event_mapColor6BoxMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseColor1Box;
    private javax.swing.JLabel baseColor1Label;
    private javax.swing.JPanel baseColor2Box;
    private javax.swing.JLabel baseColor2Label;
    private javax.swing.JPanel baseColor3Box;
    private javax.swing.JLabel baseColor3Label;
    private javax.swing.JPanel baseColor4Box;
    private javax.swing.JLabel baseColor4Label;
    private javax.swing.JPanel baseColor5Box;
    private javax.swing.JLabel baseColor5Label;
    private javax.swing.JPanel baseColor6Box;
    private javax.swing.JLabel baseColor6Label;
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel mapColor1Box;
    private javax.swing.JLabel mapColor1Label;
    private javax.swing.JPanel mapColor2Box;
    private javax.swing.JLabel mapColor2Label;
    private javax.swing.JPanel mapColor3Box;
    private javax.swing.JLabel mapColor3Label;
    private javax.swing.JPanel mapColor4Box;
    private javax.swing.JLabel mapColor4Label;
    private javax.swing.JPanel mapColor5Box;
    private javax.swing.JLabel mapColor5Label;
    private javax.swing.JPanel mapColor6Box;
    private javax.swing.JLabel mapColor6Label;
    private javax.swing.JTextField themeTitleField;
    // End of variables declaration//GEN-END:variables
}
